# This is a basic workflow to help you get started with Actions

name: Tools.TFSASAP.vNext.Voting.Production.Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Wlad-Workflow-Deployment-Migration]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.repository) }}
        run: echo "$GITHUB_CONTEXT"
  # This workflow contains a single job called "build"
  Demployment:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: Tools.TFSASAP.vNext.Voting.Production
        name: drop       
        commit: c1586e03808503ed587a6c386218a8aedb3a4943
        path: .
        # Optional, defaults to current repo
        repo: ${{github.repository}}
